config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "offers#index"

  get '/dashboard', to: "pages#dashboard"

  resources :offers, only: [:new, :create, :show, :index, :edit, :update] do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create, :index]
  end
  resources :bookings, only: [:index, :show, :update]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  validates :comment, presence: true
  validates :event_date, presence: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  CATEGORIES = %w[Musique Cinema Politique Sport].freeze

  validates :celebrity_name, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  validates :photo, presence: true

  # include PgSearch::Model
  # pg_search_scope :search_by_category_and_name,
  #   against: [:category, :celebrity_name],
  #   using: {
  #     tsearch: { prefix: true }
  # }

  include PgSearch::Model
  pg_search_scope :global_search,
  against: [ :category, :celebrity_name ],
  associated_against: {
    user: [ :address ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :offer

  validates :comment, length: { maximum: 140 }
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :offers, dependent: :destroy
  has_many :bookings, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :city, :zip_code])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :city, :zip_code])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_offer, only: %i[new create]

  def new
    # @offer = Offer.find(params[:offer_id])
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.offer = @offer
    @review = Review.new()
    @reviews = @offer.reviews
    if @booking.save
      redirect_to '/dashboard'
    else
      render 'offers/show', status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(status: params[:new_status])
    redirect_to '/dashboard'
  end


  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

  def booking_params
    params.require(:booking).permit(:event_date, :comment)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def new
    @offer = Offer.new
  end

  def show
    @users = User.all
    # @markers = @users.geocoded.map do |user|
    #   {
    #     lat: user.latitude,
    #     lng: user.longitude,
    #     info_window_html: render_to_string(partial: "info_window", locals: { user: user })
    #   }
    # end
    @offer = Offer.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    @reviews = @offer.reviews
    @markers = [{ lat: @offer.user.latitude, lng: @offer.user.longitude,  info_window_html: render_to_string(partial: "info_window", locals: { user: @offer.user }) }, { lat: current_user.latitude, lng: current_user.longitude, info_window_html: render_to_string(partial: "info_window", locals: { user: current_user }) }]
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    if params[:query].present? || params[:category].present?
      if params[:query].present?
        @offers = Offer.global_search(params[:query])
      elsif params[:category].present?
        @offers = Offer.global_search(params[:category])
      end
    else
      @offers = Offer.all
    end
    @users = User.all

  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    if @offer.update(offer_params)
      redirect_to '/dashboard'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def offer_params
    params.require(:offer).permit(:celebrity_name, :price, :category, :content, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @user_offers = current_user.offers
    @user_bookings = current_user.bookings
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_offer, only: %i[new create]
  def index

  end

  def new
    # @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.offer = @offer
    @booking = Booking.new
    @reviews = @offer.reviews

    respond_to do |format|
      if @review.save
        format.html { redirect_to offer_path(@offer) }
        format.json
      else
        format.html { render 'offers/show', status: :unprocessable_entity }
        format.json
      end
    end
  end

  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentACelebrity</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css' rel='stylesheet' />
    <link rel="shortcut icon" type="image/png" href="https://l4.tm-web-01.co.uk/lib/F521358.webp"/>



  </head>

  <body style= "background-color: #F7F7F7">
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
    <% unless action_name =="dashboard" %>
    <%= render "shared/footer" %>
    <% end %>
  </body>
</html>

app/views/offers/_info_window.html.erb
<h2><%= user.first_name %> <%= user.last_name %></h2>

app/views/offers/edit.html.erb
<div class="container">
  <h1 class= "my-5">Modifier votre offre</h1>
  <%= simple_form_for @offer do |f| %>
  <%= f.input :celebrity_name %>
  <%= f.input :short_desc %>
  <%= f.input :price %>
  <%= f.select :category, Offer::CATEGORIES %>
  <%= f.input :content %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <div class= "mb-5"></div>
</div>

app/views/offers/index.html.erb
<%= render 'shared/banner' %>

  <%= form_with url: offers_path, method: :get, class: "d-flex offset-md-4 col-4 mb-5" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Cherche ta célébrité preferée !"
    %>
    <%= submit_tag "Search", class: "btn btn-secondary" %>
  <% end %>

<div class = "container mb-5">

  <div id = "icons" class="row mb-3">

    <div class="col" style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
      <%= link_to offers_path(category: "Cinema") do %>
        <i class="fa-solid fa-film fa-2x icons" style="<%= 'color: #000000' if params[:category] == 'Cinema'%>"></i>
      <% end %>
      <p class="<%= 'fw-bold' if params[:category] == "Cinema" %>">Cinema</p>
    </div>


      <div class="col" style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
      <%= link_to offers_path(category: "Sport") do %>
      <i class="fa-solid fa-baseball-bat-ball fa-2x icons" style="<%= 'color: #000000' if params[:category] == 'Sport'%>"></i>
      <% end %>
      <p class="<%= 'fw-bold' if params[:category] == "Sport" %>">Sport</p>
    </div>

      <div class="col" style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
      <%= link_to offers_path(category: "Musique") do %>
      <i class="fa-solid fa-music fa-2x icons" style="<%= 'color: #000000' if params[:category] == 'Musique'%>"></i>
      <% end %>
      <p class="<%= 'fw-bold' if params[:category] == "Musique" %>">Musique</p>
    </div>

      <div class="col" style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
        <%= link_to offers_path(category: "Politique") do %>
      <i class="fa-solid fa-landmark fa-2x icons" style="<%= 'color: #000000' if params[:category] == 'Politique'%>"></i>
      <% end %>
      <p class="<%= 'fw-bold' if params[:category] == "Politique" %>">Politique</p>
    </div>

   <div class="col" style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
        <%= link_to offers_path(category: "") do %>
    <i class="fa-solid fa-reply-all fa-2x icons" style="<%= 'color: #000000' if params[:category] == ''%>"></i>
    <% end %>
    <p class="<%= 'fw-bold' if params[:category] == "" %>">Tous</p>
    </div>
  </div>

  <div class="align-items-center">

    <div class="row row-cols-1 row-cols-md-3 g-4" >
      <% @offers.each do |offer| %>
        <%= link_to offer_path(offer), class: "card-index" do %>
          <div class="col-1">
            <div class="card" style="width: 23rem;">
              <div class="card-info">
                <div class="d-flex justify-content-center mb-3">
                  <%= cl_image_tag offer.photo.key, width: 200, height: 200, gravity: :face, crop: :thumb, class:"rounded" %>
                </div>
              <% ratings = [] %>
              <% offer.reviews.each {|review| ratings << review.rating} %>
              <% if ratings.empty? %>
              <p><i class="fa-solid fa-star" style="color: #FEDE01"></i> - </p>
              <% else %>
              <p><i class="fa-solid fa-star" style="color: #FEDE01"></i><%= ratings.sum.fdiv(ratings.size).round(1) %></p>
              <% end %>
              <p class="celebrity mb-1"> <%= offer.celebrity_name %> </p>
              <% if offer.category == "Cinema"  %>
                <p class="text-secondary"><i class="fa-solid fa-film"></i> <%= offer.category%> </p>
              <% elsif offer.category == "Sport"  %>
                <p class="text-secondary"><i class="fa-solid fa-baseball-bat-ball"></i> <%= offer.category%> </p>
              <% elsif offer.category == "Musique"  %>
                <p class="text-secondary"><i class="fa-solid fa-music"></i> <%= offer.category%> </p>
              <% elsif offer.category == "Politique"  %>
                <p class="text-secondary"><i class="fa-solid fa-landmark"></i> <%= offer.category%> </p>
              <% end %>
              <p><%= offer.short_desc %></p>
              <p class="price"> <%= offer.price %> €</p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container">
  <h1>Devenir un sosie</h1>
  <p>Merci de compléter les informations demandées</p>
  <%= simple_form_for @offer do |f| %>
  <%= f.input :celebrity_name %>
  <%= f.input :short_desc %>
  <%= f.input :price %>
  <%= f.select :category, Offer::CATEGORIES %>
  <%= f.input :content %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/offers/show.html.erb
<div class = "container mb-5">
  <div class = "class-top d-flex justify-content-between">
    <%= cl_image_tag @offer.photo.key, height: 400, width: 400, crop: :fit, class: " img-show" %>
    <div class="map"style="width: 860px; height: 400px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <div class = "flexbox-description d-flex justify-content-between">
      <div class = "description-offer">
          <h1 class = "mt-5"> <%= @offer.celebrity_name %> </h1>
          <% ratings = [] %>
          <% @offer.reviews.each {|review| ratings << review.rating} %>
          <% if ratings.empty? %>
            <p><i class="fa-solid fa-star" style="color: #FEDE01"></i> - </p>
          <% else %>
            <p><i class="fa-solid fa-star" style="color: #FEDE01"></i><%= ratings.sum.fdiv(ratings.size).round(1) %></p>
          <% end %>
          <p> <%= @offer.short_desc %></p>
          <% if @offer.category == "Cinema"  %>
              <p class="text-secondary"><i class="fa-solid fa-film"></i> <%= @offer.category%> </p>
            <% elsif @offer.category == "Sport"  %>
              <p class="text-secondary"><i class="fa-solid fa-baseball-bat-ball"></i> <%= @offer.category%> </p>
            <% elsif @offer.category == "Musique"  %>
              <p class="text-secondary"><i class="fa-solid fa-music"></i> <%= @offer.category%> </p>
            <% elsif @offer.category == "Politique"  %>
              <p class="text-secondary"><i class="fa-solid fa-landmark"></i> <%= @offer.category%> </p>
            <% end %>
          <p> <%= @offer.content%></p>
      </div>
    <div class = "card-reservation my-5">
      <div class = "">
        <div class = "p-card">
          <p class = "available-tag">Disponible</p>
        </div>
        <div>
            <p class="element-card"> <i class="fa-solid fa-tree-city"></i>        <%= @offer.user.address %></p>
        </div>
        <div class = "price-card">
          <p> <%= @offer.price %> €</p>
        </div>
        </div>
        <div class="container mb-5">
          <%= simple_form_for [@offer, @booking], namespace: 'booking form', data: { controller: 'flatpickr' } do |f| %>
          <%= f.input :event_date, as: :string, input_html: { data: { flatpickr_target: "eventDate" } }%>
          <%= f.input :comment, placeholder: "Renseigner ici le lieu, des détails sur la prestation, ainsi que d'autres informations utiles..." %>
          <%= f.submit "Réserver", class: "btn reserv-btn" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="flexbox-description d-flex justify-content-center" data-controller="insert-review">
      <div class="card" style="width: 30rem;">
        <h2>Commentaires:</h2>
        <ul class="list-group list-group-flush" data-insert-review-target = reviews>
        <% @reviews.sort.reverse!.each do |review| %>
        <div>
          <%= render 'reviews/review', review: review %>
        </div>
        <% end %>
        </ul>
        </div>
          <div class="card align-self-start ms-5" style="width: 20rem;">
          <%= render 'reviews/form', review: @review, offer: @offer  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>Mon Dashboard</h1>

  <h2 class="mt-5">Mes réservations :</h2>
  <% @user_bookings.sort.reverse!.each do |booking| %>
    <div class="card-product my-3 mx-5">
      <%= cl_image_tag booking.offer.photo.key, height: 400, width: 400, crop: :fit %>
      <div class= "card-product-flex">
        <div class="card-product-infos ">
          <h2> <%= booking.offer.celebrity_name  %> </h2>
          <p>Date : <strong><%= booking.event_date %></strong></p>
          <p>Prix : <strong><%= booking.offer.price %> €</strong></p>
          <p>Commentaires : <strong><%= booking.comment %></strong></p>
        </div>
        <div class="pe-5">
          <% if booking.status == "Pending" %>
            <button type="button" class="btn btn-secondary" disabled><%= booking.status %></button>
          <% elsif booking.status == "Accepted"  %>
            <button type="button" class="btn btn-success" disabled><%= booking.status %></button>
          <% elsif booking.status == "Rejected"  %>
            <button type="button" class="btn btn-danger" disabled><%= booking.status %></button>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <h2 class="mt-5">Mes prestations :</h2>
  <% @user_offers.sort.reverse!.each do |offer| %>
    <div class="card-product my-3 mx-4">
      <%= cl_image_tag offer.photo.key, height: 400, width: 400, crop: :fit %>
      <div class= "card-product-flex">
        <div class="card-product-infos ">
          <h2> <%= offer.celebrity_name  %> </h2>
          <p>Event Price : <strong><%= offer.price %> €</strong></p>
          <p> <%= offer.content %></p>
        </div>
        <div class="pe-5">
          <%= link_to "edit", edit_offer_path(offer), class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
    <% offer.bookings.sort.reverse!.each do |booking| %>
      <div class="card-product my-1 mx-5">
      <div class= "card-product-flex">
        <div class="card-product-infos">
          <h2> Contrat le <%= booking.event_date  %> </h2>
          <p> Client : <strong><%= booking.user.first_name %> <%= booking.user.last_name %> </strong></p>
          <p> Adresse : <%= booking.user.address %></p>

        </div>
        <div class="card-product-infos">
          <p> Email : <%= booking.user.email %></p>
          <p> Commentaires : <%= booking.comment %></p>
        </div>
        <div class="pe-5">
          <% if booking.status == "Pending"%>
            <%= link_to "Accepter", booking_path(booking, new_status: "Accepted"), data: {turbo_method: :patch}, class: "btn btn-success" %>
            <%= link_to "Refuser", booking_path(booking, new_status: "Rejected"), data: {turbo_method: :patch}, class: "btn btn-danger" %>
          <% elsif booking.status == "Accepted" %>
            <button type="button" class="btn btn-success" disabled><%= booking.status %></button>
          <% elsif booking.status == "Rejected" %>
            <button type="button" class="btn btn-danger" disabled><%= booking.status %></button>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [offer, review], namespace: 'review form', data: {insert_review_target: "form", action: "submit->insert-review#send"}  do |f| %>
  <%= f.input :comment, label: 'Ajoute un commentaire' %>
  <%= f.input :rating, collection: (1..5).to_a, label: "Donne une note", input_html: {data: {controller: "star-rating"}} %>
  <%= f.submit :submit, class: "btn btn-success" %>
<% end %>

app/views/reviews/_review.html.erb
<li class="list-group-item"><% review.rating.times do %>
    <i class="fa-solid fa-star" style="color: #FEDE01"></i>
  <% end %>
  <p class="small">less than <%= ((Time.now - review.created_at)/60).to_i %> minutes ago</p>
  <p><i class="fa-solid fa-quote-right"></i> <%= review.comment %></p>
</li>

app/views/reviews/new.html.erb
  <%= simple_form_for [@offer, @review], namespace: 'review form' do |f| %>
    <%= f.input :comment %>
    <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>
    <%= f.submit :submit, class: "btn btn-success" %>
  <% end %>

app/views/shared/_banner.html.erb
<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.2)), url(https://static.wixstatic.com/media/388b7a_83d47312eef94a27a7d337a1a1eae3fa.jpg/v1/fill/w_980,h_240,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/388b7a_83d47312eef94a27a7d337a1a1eae3fa.jpg);">
  <div class="container">
    <h1>Rent Your Celebs !</h1>
    <p><span data-controller="typed-js"></span></p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" class="vague">
    <path fill="#a2d9ff" fill-opacity="1" d="M0,96L60,106.7C120,117,240,139,360,138.7C480,139,600,117,720,117.3C840,117,960,139,1080,138.7C1200,139,1320,117,1380,106.7L1440,96L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"></path>
    </svg> %>
<div class="footer">
  <div class = "container">
    <div class="footer-links d-flex justify-content-center pt-1">
      <ul>
      <li> <a href="#">© 2023 Rent_A_Celebrity, Inc.</a></li>
      <li> <a href="#">Confidentialité</a></li>
      <li> <a href="#">Conditions générales</a></li>
      <li> <a href="#">Plan du site</a></li>
      </ul>
    </div>
    <div class="footer-copyright text-center 3">
          This footer is made with <i class="fas fa-heart"></i> at Le Wagon
        </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to offers_path, class: "navbar-brand" do %>
      <%= image_tag "https://l4.tm-web-01.co.uk/lib/F521358.webp" %>
      <% if user_signed_in? && current_user.first_name  %>
      <span class="navbar-text">Bienvenue <%= current_user.first_name.capitalize %></span>
      <% end %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <%# <% if user_signed_in? %>
            <li class="nav-item active">
              <strong><%= link_to "Vous êtes un sosie?", new_offer_path, class: "nav-link" %></strong>
            </li>
            <li class="nav-item active">
              <%= link_to "Les sosies", offers_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrnv4-74fOG5XFFrhzG-ehFHZFdGzC4pj5CQ&usqp=CAU", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Mon profil", :edit_user_registration, class: "dropdown-item" %>
                <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <%# else %>
            <!--li class="nav-item"-->
              <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
            <!--/li-->
          <%# end %>
         </ul>
    </div>
  </div>
</div>

app/views/shared/navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>